log_timestamp_format %Y-%m-%dT%H:%M:%S

allow_anonymous false
password_file /etc/mosquitto/passwd

listener 1883
protocol mqtt

listener 8884
protocol websockets
certfile /etc/yunohost/certs/captain.010101010101.xyz/crt.pem
keyfile /etc/yunohost/certs/captain.010101010101.xyz/key.pem
require_certificate false
